const state={projects:[],category:'Semua',query:'',current:null,objectUrls:[],scriptUrls:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const infoPages={
  petunjuk:{kicker:'PANDUAN',title:'Petunjuk Penggunaan',html:`<h3>1. Tambahkan proyek</h3><div class="info-step"><b>1</b><span>Klik <strong>Tambah Proyek</strong> dan pilih folder yang memiliki <code>index.html</code>.</span></div><div class="info-step"><b>2</b><span>Pilih kategori, tulis nama dan deskripsi, lalu tambahkan thumbnail bila tersedia.</span></div><div class="info-step"><b>3</b><span>Proyek disimpan di penyimpanan lokal browser. Tidak perlu server atau internet.</span></div><h3>2. Menjalankan proyek</h3><p>Klik <strong>Buka</strong>. BRIAN akan menampilkan project melalui player dengan navigasi kecil di luar aplikasi sehingga project tetap standalone.</p><h3>3. Mengedit proyek</h3><p>Klik <strong>Editor</strong> pada kartu proyek untuk mengubah nama, kategori, deskripsi, dan thumbnail tanpa mengubah file inti proyek.</p><h3>Catatan kompatibilitas</h3><p>Gunakan project HTML yang memakai aset relatif di dalam foldernya sendiri. Untuk pengalaman offline terbaik, simpan semua CSS, JavaScript, gambar, audio, dan video bersama project.</p>`},
  syarat:{kicker:'INFORMASI',title:'Syarat & Ketentuan',html:`<h3>Penggunaan</h3><p>BRIAN Learning & Media Studio disediakan sebagai alat pengelolaan koleksi karya digital secara lokal. Pengguna bertanggung jawab atas isi project yang diimpor.</p><h3>Kepemilikan karya</h3><p>Jangan mengimpor materi yang melanggar hak cipta, privasi, atau ketentuan penggunaan pihak lain. Metadata dan file project tetap berada pada perangkat pengguna.</p><h3>Batasan</h3><p>Performa dan kompatibilitas bergantung pada browser, ukuran project, serta teknologi yang digunakan di dalam project standalone.</p>`},
  privasi:{kicker:'PRIVASI',title:'Kebijakan Privasi',html:`<h3>Data lokal</h3><p>Versi offline BRIAN menyimpan daftar proyek, metadata, thumbnail, dan file project di penyimpanan lokal browser menggunakan IndexedDB.</p><h3>Tidak ada server</h3><p>Versi ini tidak mengirim koleksi Anda ke server BRIAN. Karena itu data hanya tersedia pada browser/perangkat tempat koleksi disimpan.</p><h3>Pengelolaan data</h3><p>Anda dapat menghapus project dari koleksi melalui Editor. Menghapus data situs browser juga dapat menghapus koleksi lokal tersebut.</p>`}
};
function toast(message,type='success'){const t=$('#toast');t.textContent=message;t.className=`toast ${type}`;setTimeout(()=>t.classList.add('hidden'),2600);}
async function init(){state.projects=(await AppDB.all()).sort((a,b)=>(b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0));bind();render();}
function bind(){
  $$('#sideNav .side-link[data-category],#topChips .filter-chip').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));
  $('#collectionSearch').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();$('#searchClear').classList.toggle('hidden',!state.query);render();});
  $('#searchClear').addEventListener('click',()=>{$('#collectionSearch').value='';state.query='';$('#searchClear').classList.add('hidden');render();});
  $('#openAddTop').addEventListener('click',()=>openProjectDialog());
  document.addEventListener('click',e=>{const info=e.target.closest('[data-info]');if(info){e.preventDefault();openInfo(info.dataset.info);return;}});
  document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)$(('#'+close.dataset.close)).classList.add('hidden');const edit=e.target.closest('[data-edit]');if(edit)openEditor(edit.dataset.edit);const open=e.target.closest('[data-open]');if(open)openPlayer(open.dataset.open);const del=e.target.closest('[data-delete]');if(del)deleteProject(del.dataset.delete);const share=e.target.closest('[data-share]');if(share)shareProject(share.dataset.share);});
  $('#projectForm').addEventListener('submit',saveProject);$('#projectFolder').addEventListener('change',updateFolderLabel);$('#projectThumb').addEventListener('change',previewInput);['#projectName','#projectCategory','#projectDesc'].forEach(sel=>$(sel).addEventListener('input',updatePreview));
  $('#playerBack').addEventListener('click',closePlayer);$('#playerClose').addEventListener('click',closePlayer);$('#floatBack').addEventListener('click',closePlayer);$('#floatBack2').addEventListener('click',closePlayer);$('#playerReload').addEventListener('click',reloadPlayer);$('#floatReload').addEventListener('click',reloadPlayer);$('#playerFull').addEventListener('click',toggleFullscreen);$('#floatFull').addEventListener('click',toggleFullscreen);$('#floatMore').addEventListener('click',()=>$('#floatMenu').classList.toggle('hidden'));
  $('#projectDialog').addEventListener('click',e=>{if(e.target.id==='projectDialog')$('#projectDialog').classList.add('hidden')});$('#infoDialog').addEventListener('click',e=>{if(e.target.id==='infoDialog')$('#infoDialog').classList.add('hidden')});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#playerOverlay').classList.contains('hidden'))closePlayer();else{$('#projectDialog').classList.add('hidden');$('#infoDialog').classList.add('hidden');}}});
}
function setCategory(cat){state.category=cat;$$('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===cat));const title=cat==='Semua'?'Semua Aplikasi':cat==='VLab/Simulasi'?'VLab / Simulasi':cat;$('#catalogTitle').textContent=title;$('#catalogSubtitle').textContent=cat==='Semua'?'Kelola seluruh karya digital Anda dari satu ruang yang ringan, modern, dan tetap offline.':`Menampilkan koleksi ${title} yang tersimpan secara lokal.`;render();}
function filtered(){return state.projects.filter(p=>(state.category==='Semua'||p.category===state.category)&&(!state.query||`${p.title} ${p.category} ${p.description}`.toLowerCase().includes(state.query)));}
function render(){const list=filtered();$('#visibleCount').textContent=list.length;$('#allCount').textContent=state.projects.length;$('#gameCount').textContent=state.projects.filter(p=>p.category==='Gim Edu').length;$('#mpiCount').textContent=state.projects.filter(p=>p.category==='MPI').length;$('#vlabCount').textContent=state.projects.filter(p=>p.category==='VLab/Simulasi').length;$('#appCount').textContent=state.projects.filter(p=>p.category==='Aplikasi').length;const grid=$('#catalogGrid');grid.innerHTML='';if(!list.length){grid.innerHTML=`<div class="empty-state"><div class="empty-icon">＋</div><h3>${state.query?'Tidak ada proyek yang cocok':'Belum ada proyek di koleksi'}</h3><p>${state.query?'Coba kata kunci lain atau pilih kategori berbeda.':'Koleksi masih kosong. Tambahkan folder project HTML Anda untuk mulai membangun perpustakaan digital sendiri.'}</p><button class="btn-primary empty-cta" id="emptyAdd">＋ Tambah Proyek</button></div>`;$('#emptyAdd').addEventListener('click',()=>openProjectDialog());return;}for(const p of list){const card=document.createElement('article');card.className='catalog-card';card.innerHTML=`<div class="catalog-thumb"><img src="${p.thumbnail||fallbackThumb(p.title)}" alt="Thumbnail ${esc(p.title)}"><div class="thumb-overlay"></div><span class="type-badge">${esc(p.category)}</span><button class="card-share" data-share="${esc(p.id)}" title="Bagikan">↗</button></div><div class="catalog-card-body"><h3>${esc(p.title)}</h3><p>${esc((p.description||'Proyek HTML offline.').slice(0,100))}</p><div class="card-actions"><button class="open-card" data-open="${esc(p.id)}">▶ Buka</button><button class="edit-card" data-edit="${esc(p.id)}">✦ Editor</button><button class="delete-card" data-delete="${esc(p.id)}" title="Hapus proyek">🗑</button></div></div>`;grid.appendChild(card);}}
function openProjectDialog(project=null){$('#projectDialog').classList.remove('hidden');$('#projectForm').reset();$('#editingId').value='';$('#dialogKicker').textContent='TAMBAH PROYEK';$('#dialogTitle').textContent='Tambahkan karya baru';$('#dialogSubtitle').textContent='Pilih folder yang memiliki index.html beserta asetnya.';$('#importFields').classList.remove('hidden');$('#selectedFiles').textContent='Belum ada folder dipilih.';if(project){$('#dialogKicker').textContent='EDITOR PROYEK';$('#dialogTitle').textContent='Edit detail proyek';$('#dialogSubtitle').textContent='Metadata dapat diperbarui tanpa mengubah file inti project.';$('#editingId').value=project.id;$('#projectName').value=project.title;$('#projectCategory').value=project.category;$('#projectDesc').value=project.description||'';$('#importFields').classList.add('hidden');}updatePreview();}
function openEditor(id){const p=state.projects.find(x=>x.id===id);if(p)openProjectDialog(p);}
function updateFolderLabel(){const files=[...$('#projectFolder').files];$('#selectedFiles').textContent=files.length?`${files.length} file dipilih · ${files[0].webkitRelativePath.split('/')[0]}`:'Belum ada folder dipilih.';}
function updatePreview(){const name=$('#projectName').value.trim()||'Nama proyek';$('#previewName').textContent=name;$('#previewCategory').textContent=$('#projectCategory').value;$('#previewDesc').textContent=$('#projectDesc').value.trim()||'Deskripsi proyek akan muncul di sini.';if(!$('#previewThumb').style.backgroundImage)$('#previewThumb').style.backgroundImage=`url("${fallbackThumb(name)}")`;}
async function previewInput(){const f=$('#projectThumb').files[0];if(f)$('#previewThumb').style.backgroundImage=`url("${await dataUrl(f)}")`;}
async function saveProject(e){e.preventDefault();const id=$('#editingId').value;const name=$('#projectName').value.trim();const category=$('#projectCategory').value;const description=$('#projectDesc').value.trim();if(!name){toast('Nama proyek wajib diisi.','error');return;}if(id){const p=state.projects.find(x=>x.id===id);if(!p)return;const thumb=$('#projectThumb').files[0];p.title=name;p.category=category;p.description=description;p.updatedAt=Date.now();if(thumb)p.thumbnail=await dataUrl(thumb);else if(!p.thumbnail)p.thumbnail=fallbackThumb(name);await AppDB.put(p);toast('Detail proyek diperbarui.');closeProjectDialog();await refresh();return;}const files=[...$('#projectFolder').files];if(!files.length){toast('Pilih folder proyek terlebih dahulu.','error');return;}const indexFile=files.find(f=>/\/index\.(html?|HTML?)$/.test('/'+f.webkitRelativePath))||files.find(f=>/^index\.(html?|HTML?)$/i.test(f.name));if(!indexFile){toast('Folder harus memiliki index.html atau index.htm.','error');return;}const entries={};for(const f of files){const path=f.webkitRelativePath.split('/').slice(1).join('/')||f.name;entries[normalizePath(path)]=await f.arrayBuffer();}const thumbFile=$('#projectThumb').files[0]||files.find(f=>/\/(?:thumbnail|cover)\.(png|jpe?g|webp|svg)$/i.test('/'+f.webkitRelativePath));const rec={id:'project-'+Date.now().toString(36)+Math.random().toString(36).slice(2,7),title:name,category,description,thumbnail:thumbFile?await dataUrl(thumbFile):fallbackThumb(name),files:entries,entry:(indexFile.webkitRelativePath.split('/').slice(1).join('/')||indexFile.name),createdAt:Date.now(),updatedAt:Date.now()};rec.entry=rec.entry.toLowerCase()==='index.htm'?'index.htm':'index.html';await AppDB.put(rec);toast('Proyek berhasil ditambahkan ke koleksi lokal.');closeProjectDialog();await refresh();}
function closeProjectDialog(){$('#projectDialog').classList.add('hidden');}
async function refresh(){state.projects=(await AppDB.all()).sort((a,b)=>(b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0));render();}
async function deleteProject(id){const p=state.projects.find(x=>x.id===id);if(!p)return;if(confirm(`Hapus “${p.title}” dari koleksi lokal?`)){await AppDB.del(id);toast('Proyek dihapus dari koleksi.');await refresh();}}
async function shareProject(id){const p=state.projects.find(x=>x.id===id);if(!p)return;const text=`${p.title}\n${p.category}\n${p.description||''}`;try{if(navigator.share)await navigator.share({title:p.title,text});else{await navigator.clipboard?.writeText(text);toast('Info proyek disalin ke clipboard.');}}catch{} }
function openInfo(key){const p=infoPages[key]||infoPages.petunjuk;$('#infoKicker').textContent=p.kicker;$('#infoTitle').textContent=p.title;$('#infoContent').innerHTML=p.html;$('#infoDialog').classList.remove('hidden');}
function cleanupUrls(){state.objectUrls.forEach(u=>URL.revokeObjectURL(u));state.scriptUrls.forEach(u=>URL.revokeObjectURL(u));state.objectUrls=[];state.scriptUrls=[];}
async function openPlayer(id){const p=state.projects.find(x=>x.id===id);if(!p)return;state.current=p;cleanupUrls();$('#playerTitle').textContent=p.title;$('#playerOverlay').classList.remove('hidden');$('#floatMenu').classList.add('hidden');document.body.style.overflow='hidden';try{const files=new Map(Object.entries(p.files||{}).map(([k,v])=>[normalizePath(k),v]));const entry=files.has(normalizePath(p.entry||'index.html'))?normalizePath(p.entry||'index.html'):(files.has('index.html')?'index.html':'index.htm');const {html,objectUrls}=await buildPlayableDocument(entry,files);state.objectUrls=objectUrls;$('#projectFrame').srcdoc=html;}catch(err){console.error(err);$('#projectFrame').srcdoc=`<!doctype html><html><body style="font-family:Arial,sans-serif;padding:40px;color:#234">Gagal membuka project.<br><br>${esc(err.message)}</body></html>`;}}
function reloadPlayer(){if(state.current){const id=state.current.id;openPlayer(id)}}
function closePlayer(){cleanupUrls();$('#playerOverlay').classList.add('hidden');$('#projectFrame').srcdoc='';$('#floatMenu').classList.add('hidden');state.current=null;document.body.style.overflow='';}
function toggleFullscreen(){const stage=$('#playerStage');if(!document.fullscreenElement)stage.requestFullscreen?.();else document.exitFullscreen?.();}
document.addEventListener('DOMContentLoaded',init);
